// Digital Menu Creation API
// Creates and manages digital menus with QR codes

const { insert, findById, findAll, update, remove } = require('../../lib/db');
const { checkUsageLimit } = require('../../lib/usage-tracker');

// Tier limits for menus
const TIER_LIMITS = {
  starter: { menus: 1 },
  professional: { menus: -1 },
  enterprise: { menus: -1 }
};

/**
 * Create a new digital menu
 * @param {Object} params - Menu creation parameters
 * @param {number} params.restaurant_id - Restaurant ID
 * @param {string} params.name - Menu name
 * @param {Array} params.items - Menu items array
 * @param {Object} params.settings - Menu settings (theme, layout, etc.)
 * @returns {Promise<Object>} Created menu
 */
async function createMenu({ restaurant_id, name, items = [], settings = {} }) {
  // Get restaurant and subscription
  const restaurant = await findById('restaurants', restaurant_id, 'restaurant_id');
  if (!restaurant) {
    throw new Error('Restaurant not found');
  }
  
  const subscriptions = await findAll('subscriptions', { 
    restaurant_id: parseInt(restaurant_id), 
    status: 'active' 
  });
  
  if (subscriptions.length === 0) {
    throw new Error('No active subscription found');
  }
  
  const subscription = subscriptions[0];
  const limits = TIER_LIMITS[subscription.tier] || {};
  
  // Check menu limit
  if (limits.menus !== -1) {
    const existingMenus = await findAll('content_assets', {
      restaurant_id: parseInt(restaurant_id),
      type: 'menu'
    });
    
    if (existingMenus.length >= limits.menus) {
      throw new Error(`Menu limit reached. ${limits.menus} menu(s) allowed on ${subscription.tier} plan.`);
    }
  }
  
  // Generate QR code URL (will be generated by frontend or QR service)
  const qrCodeUrl = `/menus/qr/${restaurant_id}/${Date.now()}`;
  const menuUrl = `/menus/${restaurant_id}/${Date.now()}`;
  
  // Create menu content asset
  const menu = await insert('content_assets', {
    restaurant_id: parseInt(restaurant_id),
    type: 'menu',
    url: menuUrl,
    title: name,
    description: `Digital menu: ${name}`,
    metadata: {
      items: items,
      settings: settings,
      qr_code_url: qrCodeUrl,
      created_at: new Date().toISOString()
    }
  });
  
  return {
    menu_id: menu.asset_id,
    restaurant_id: parseInt(restaurant_id),
    name,
    menu_url: menuUrl,
    qr_code_url: qrCodeUrl,
    items: items,
    settings: settings,
    created_at: menu.created_at
  };
}

/**
 * Get menu by ID
 */
async function getMenu(menu_id) {
  const menu = await findById('content_assets', menu_id, 'asset_id');
  if (!menu || menu.type !== 'menu') {
    throw new Error('Menu not found');
  }
  return menu;
}

/**
 * List all menus for a restaurant
 */
async function listMenus(restaurant_id) {
  return await findAll('content_assets', {
    restaurant_id: parseInt(restaurant_id),
    type: 'menu'
  }, 'created_at DESC');
}

/**
 * Update menu
 */
async function updateMenu(menu_id, updates) {
  const menu = await findById('content_assets', menu_id, 'asset_id');
  if (!menu || menu.type !== 'menu') {
    throw new Error('Menu not found');
  }
  
  // Update metadata
  const currentMetadata = menu.metadata || {};
  const updatedMetadata = {
    ...currentMetadata,
    ...(updates.items && { items: updates.items }),
    ...(updates.settings && { settings: { ...currentMetadata.settings, ...updates.settings } })
  };
  
  return await update('content_assets', menu_id, {
    title: updates.name || menu.title,
    metadata: updatedMetadata
  }, 'asset_id');
}

/**
 * Delete menu
 */
async function deleteMenu(menu_id) {
  const menu = await findById('content_assets', menu_id, 'asset_id');
  if (!menu || menu.type !== 'menu') {
    throw new Error('Menu not found');
  }
  
  return await remove('content_assets', menu_id, 'asset_id');
}

module.exports = {
  createMenu,
  getMenu,
  listMenus,
  updateMenu,
  deleteMenu
};
